/**
 * @file Server-side SSR E2E test.
 *
 * This test demonstrates the SERVER phase of SSR:
 * 1. Import shared component definition
 * 2. Call renderElement() to serialize to HTML string
 * 3. Output the HTML for client consumption
 *
 * Run with: npm run build && node test/ssr-e2e.mjs
 *
 * The output HTML is written to examples/kitchensink/ssr-e2e-output.js
 * which is then consumed by the Playwright test.
 */

import { renderElement } from '../build/hyperElement.ssr.mjs';
import { tagName, definition } from '../examples/kitchensink/ssr-e2e-component.mjs';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

async function runServerPhase() {
  console.log('='.repeat(50));
  console.log('SSR E2E Test - Server Phase');
  console.log('='.repeat(50));

  // Phase 1: SSR Define - Import component definition
  console.log('\n[Phase 1] SSR Define: Imported component definition');
  console.log(`  Tag name: ${tagName}`);
  console.log(`  Has render: ${typeof definition.render === 'function'}`);

  // Phase 2: Serialize - Render to HTML string
  console.log('\n[Phase 2] Serialize: Calling renderElement()...');

  const html = await renderElement(tagName, {
    attrs: {},
    render: definition.render,
  });

  console.log(`  Output HTML: ${html}`);

  // Write output for client test to consume
  const outputPath = join(__dirname, '..', 'examples', 'kitchensink', 'ssr-e2e-output.js');
  writeFileSync(
    outputPath,
    `/**\n * @file Auto-generated SSR output for e2e tests.\n * Generated by test/ssr-e2e.mjs - DO NOT EDIT.\n */\nexport const ssrHtml = ${JSON.stringify(html)};\n`
  );

  console.log(`\n[Output] Written to: ${outputPath}`);
  console.log('\n' + '='.repeat(50));
  console.log('Server phase complete. Run Playwright to test client phases.');
  console.log('='.repeat(50));
}

runServerPhase().catch((err) => {
  console.error('Server phase failed:', err);
  process.exit(1);
});
